apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: cube-api
  labels:
    app: cube-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cube-api
  template:
    metadata:
      annotations:
      labels:
        app: cube-api
    spec:
      containers:
      - name: cube-api
        image: cubejs/cube:latest
        ports:
        - containerPort: 4000
        env:
        - name: CUBEJS_DEV_MODE
          value: "false"
        - name: CUBEJS_CUBESTORE_HOST
          value: "cubestore-router"
        - name: CUBEJS_REDIS_URL
          value: "redis://keydb:6379"
        - name: CUBEJS_API_SECRET
          value: "rx5fR6tbS43Qg5gk"
        - name: CUBEJS_DB_TYPE
          value: "postgres"
        - name: CUBEJS_DB_HOST
          value: "postgres"
        - name: CUBEJS_DB_NAME
          value: "postgresdb"
        - name: CUBEJS_DB_USER
          value: "postgresadmin"
        - name: CUBEJS_DB_PASS
          value: "WZ9edj9jgCZD7jbe"
        - name: CUBEJS_DB_SSL
          value: "false"
        volumeMounts:
        - mountPath: /cube/conf
          name: cube-api-pvc-0
      volumes:
      - name: cube-api-pvc-0
        persistentVolumeClaim:
          claimName: cube-api-pvc-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cube-api-pvc-0
  name: cube-api-pvc-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: cube-api
  name: cube-api
spec:
  ports:
  - name: "4000"
    port: 4000
    targetPort: 4000
  selector:
    app: cube-api
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: cubejs
  annotations:
    kubernetes.io/ingress.class: nginx
    kubernetes.io/tls-acme: 'true'
    nginx.ingress.kubernetes.io/ssl-redirect: 'true'
    nginx.ingress.kubernetes.io/force-ssl-redirect: 'true'
spec:
  rules:
    - host: cubejs.example.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: cube-api
                port:
                  number: 4000
  tls:
    - hosts:
      - cubejs.example.com
      secretName: cubejs.example.com-tls