apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: cubestore-router
  labels:
    app: cubestore-router
spec:
  replicas: 1
  selector:
    matchLabels:
      app: cubestore-router
  template:
    metadata:
      annotations:
      labels:
        app: cubestore-router
    spec:
      containers:
      - name: cubestore-router
        image: cubejs/cubestore:latest
        ports:
        - containerPort: 9999
        - containerPort: 3030
        env:
        - name: CUBESTORE_WORKERS
          value: "cubestore-worker-1:10001,cubestore-worker-2:10002"
        - name: CUBESTORE_S3_BUCKET
          value: "<BUCKET_NAME_IN_S3>"
        - name: CUBESTORE_S3_REGION
          value: "<BUCKET_REGION_IN_S3>"
        - name: CUBESTORE_AWS_ACCESS_KEY_ID
          value: "<AWS_ACCESS_KEY_ID>"
        - name: CUBESTORE_AWS_SECRET_ACCESS_KEY
          value: "<AWS_SECRET_ACCESS_KEY>"
        - name: CUBESTORE_META_PORT
          value: "9999"
        - name: CUBESTORE_SERVER_NAME
          value: "cubestore-router:9999"
        volumeMounts:
        - mountPath: /cube/data
          name: cubestore-router-pvc-0
      volumes:
      - name: cubestore-router-pvc-0
        persistentVolumeClaim:
          claimName: cubestore-router-pvc-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: cubestore-router-pvc-0
  name: cubestore-router-pvc-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: cubestore-router
  name: cubestore-router
spec:
  ports:
  - name: "9999"
    port: 9999
    targetPort: 9999
  - name: "3030"
    port: 3030
    targetPort: 3030
  selector:
    app: cubestore-router