apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
  name: postgres
  labels:
    app: postgres
spec:
  replicas: 1
  selector:
    matchLabels:
      app: postgres
  template:
    metadata:
      annotations:
      labels:
        app: postgres
    spec:
      containers:
      - name: postgres
        image: postgres:13.4
        ports:
        - containerPort: 5432
        env:
        - name: POSTGRES_DB
          value: "postgresdb"
        - name: POSTGRES_USER
          value: "postgresadmin"
        - name: POSTGRES_PASSWORD
          value: "WZ9edj9jgCZD7jbe"
        volumeMounts:
        - mountPath: /var/lib/postgresql/data
          name: postgres-pvc-0
          subPath: postgres
      volumes:
      - name: postgres-pvc-0
        persistentVolumeClaim:
          claimName: postgres-pvc-0
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: postgres-pvc-0
  name: postgres-pvc-0
spec:
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 10Gi
---
apiVersion: v1
kind: Service
metadata:
  annotations:
  labels:
    app: postgres
  name: postgres
spec:
  ports:
  - name: "5432"
    port: 5432
    targetPort: 5432
  selector:
    app: postgres